__title__ = 'QuickConfigTemplates'
__description__ = 'Creates configuration from YAML'
__author__ = 'Benjamin P. Trachtenberg'
__copyright__ = "Copyright (c) 2018 - 2021 Benjamin P. Trachtenberg"
__credits__ = 'Benjamin P. Trachtenberg'
__license__ = 'MIT'
__status__ = 'prod'
__version_info__ = (2, 0, 0)
__version__ = '.'.join(map(str, __version_info__))
__maintainer__ = 'Benjamin P. Trachtenberg'
__email__ = 'e_ben_75-python@yahoo.com'
